#!/usr/bin/perl
# A small tool to generate a random DFA
use List::Util qw(shuffle);
use strict;
use warnings;

die "Usage: ./gendea [number of states] [length of alphabet]\n" unless @ARGV;

my $states = shift;
my $sigman = shift;
die "Statesnumber must be numeric.\n" unless $states =~ /\d+/;
die "Sigmalength must be numeric.\n" unless $sigman =~ /\d+/;

#print final states
print((join " ", (shuffle 1...$states)[0..rand $states]),"\n");

for(1..$states) {
	print join " ", map {1 + int rand $states} (1..$sigman);
	print "\n";
}
